# Generated by Django 4.2 on 2024-09-09 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chauffeur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.PositiveIntegerField()),
                ('couleur', models.CharField(max_length=50)),
                ('immatriculation', models.CharField(max_length=100, unique=True)),
                ('kilometrage', models.PositiveIntegerField()),
                ('date_achat', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicules_photos/')),
                ('chauffeur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicule', to='chauffeur.chauffeur')),
            ],
        ),
    ]
