# Generated by Django 4.2 on 2024-09-09 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chauffeur', '0001_initial'),
        ('vehicule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueChauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('ancien_chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques_anciennes', to='chauffeur.chauffeur')),
                ('nouveau_chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques_nouveaux', to='chauffeur.chauffeur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='vehicule.vehicule')),
            ],
        ),
    ]
