# Generated by Django 4.2 on 2024-09-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chauffeur', '0002_chauffeur_email_alter_chauffeur_numero_piece_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeur',
            name='numero_piece',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
