# Generated by Django 4.2 on 2024-09-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chauffeur', '0003_alter_chauffeur_numero_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
