# Generated by Django 4.2 on 2024-09-15 23:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chauffeur', '0004_chauffeur_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueLicenciement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_licenciement', models.DateTimeField(default=django.utils.timezone.now)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chauffeur.chauffeur')),
            ],
        ),
    ]
