# Generated by Django 4.2 on 2024-09-09 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chauffeur', '0003_alter_chauffeur_numero_piece'),
        ('vehicule', '0002_historiquechauffeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenuJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chauffeur.chauffeur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicule.vehicule')),
            ],
            options={
                'unique_together': {('chauffeur', 'vehicule', 'date')},
            },
        ),
    ]
